plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - /docs/CODE-OF-CONDUCT.md
  - /docs/CONTRIBUTING.md
  - /docs/CheatSheet-Template.md
  - /docs/HOW-TO.md

  - /CheatSheets/JavaScript-CheatSheet.md
  - /CheatSheets/Numpy-cheatsheet.md
  - /CheatSheets/Python-cheatsheet.md
  - /CheatSheets/angular-cheatsheet.md
  - /CheatSheets/bash_cheatsheet.md
  - /CheatSheets/chrome-devtools-cheatsheet.md
  - /CheatSheets/cmd-cheatsheet.md
  - /CheatSheets/conda-cheatsheet.md
  - /CheatSheets/configure-react-cheatsheet.md
  - /CheatSheets/cpp-stl-cheatsheet.md
  - /CheatSheets/css-cheatsheet.md
  - /CheatSheets/docker-cheatsheet.md
  - /CheatSheets/extension-cheatsheet.md
  - /CheatSheets/git-cheatsheet.md
  - /CheatSheets/html-cheatsheet.md
  - /CheatSheets/java-cheatsheet.md
  - /CheatSheets/kotlin-cheatsheet.md
  - /CheatSheets/linux-cheatsheet.md
  - /CheatSheets/markdown-cheatsheet.md
  - /CheatSheets/mongodb-cheatsheet.md
  - /CheatSheets/nodeJs-cheatsheet.md
  - /CheatSheets/npm-cheatsheet.md
  - /CheatSheets/npx-cheetsheet.md
  - /CheatSheets/nvm-cheatsheet.md
  - /CheatSheets/pandas-cheatsheet.md
  - /CheatSheets/php-cheatsheet.md
  - /CheatSheets/react-cheatsheet.md
  - /CheatSheets/regex-cheatsheet.md
  - /CheatSheets/sklearn-cheatsheet.md
  - /CheatSheets/sql-cheatsheets.md
  - /CheatSheets/terraform-cheatsheet.md
  - /CheatSheets/vim-editor-cheatsheet.md
  - /CheatSheets/vscode-cheatsheet.md
  - /CheatSheets/windows-cheatsheet.md
  - /CheatSheets/yarn-cheatsheet.md
